FROM php-fpm:7.3


#COPY php-fpm/scripts/ /usr/local/bin
#RUN chmod +x /usr/local/bin/ssh.sh

# RUN ssh -fNg -L ${DATABASE_PORT}:127.0.0.1:${DATABASE_PORT} ${DATABASE_LOGIN}@${DATABASE_HOST}
# CMD ssh -fNg -L 3306:127.0.0.1:3306 root@47.101.202.230