---
kind: Service
apiVersion: v1
metadata:
  name: service-user
spec:
  selector:
    app: nginx
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-user
spec:
  selector:
    matchLabels:
      app: nginx
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
        track: stable
    spec:
      # restartPolicy: Never
      volumes:
        - name: project-data
          emptyDir: {}

      containers:
        - name: user-app
          image: redeploy/service-user-app:latest
          volumeMounts:
            - name: project-data
              mountPath: /var/www/html
          stdin: true 
          tty: true

        - name: php
          image: redeploy/php:7.3-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: project-data
              mountPath: /var/www/html

        - name: nginx
          image: redeploy/nginx:stable
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: project-data
              mountPath: /var/www/html

        # - name: mysql
        #   image: redeploy/mysql:latest
        #
        # - name: redis
        #   image: redeploy/redis:latest
