---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
  - protocol: TCP
    port: 9000

---
kind: Service
apiVersion: v1
metadata:
  name: service-user-nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      # targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30080
  type: LoadBalancer

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: code
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    server {
        listen 80;
        #listen 8080;
        server_name  localhost;
        root   /var/www/html/public/;
        index  index.html index.htm index.php;

        error_log  /var/log/nginx/error.log  warn;
        access_log /var/log/nginx/access.log;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
       error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /var/www/html/public;
        }
        location ~ \.php$ {
            fastcgi_pass   php:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME /var/www/html/public/$fastcgi_script_name;

            include        fastcgi_params;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-user
spec:
  selector:
    matchLabels:
      app: nginx
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
        track: stable
    spec:
      # restartPolicy: Never
      volumes:
        - name: code
          emptyDir: {}
      #     hostPath:
      #       # directory location on host
      #       path: /var/www/html

          # persistentVolumeClaim:
          #   claimName: code
        - name: config
          configMap:
            name: nginx-config
            items:
            - key: config
              path: default.conf

      initContainers:
        - name: user-app
          image: redeploy/service-user-app:1.0
          command: [bash, -c]
          args: ["cp -r /var/www/html/* /data"]
          imagePullPolicy: Always
          volumeMounts:
            - name: code
              mountPath: /data
          # stdin: true
          # tty: true

      containers:
        # - name: user-app
        #   image: redeploy/service-user-app:1.0
        #   volumeMounts:
        #     - name: code
        #       mountPath: /var/www/html
        #   stdin: true
        #   tty: true

        - name: php
          image: redeploy/php:rp-7.3-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: code
              mountPath: /var/www/html

        - name: nginx
          image: redeploy/nginx:rp-1.16-p
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /var/www/html
            - name: config
              mountPath: /etc/nginx/conf.d
        # - name: mysql
        #   image: redeploy/mysql:latest
        #
        # - name: redis
        #   image: redeploy/redis:latest
