---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
  - protocol: TCP
    port: 9000

---
kind: Service
apiVersion: v1
metadata:
  name: service-user-nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30080
  type: LoadBalancer

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: code
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: do-block-storage



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service-user
spec:
  selector:
    matchLabels:
      app: nginx
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
        track: stable
    spec:
      # restartPolicy: Never
      volumes:
        - name: code
          hostPath:
            # directory location on host
            path: /var/www/html

          # persistentVolumeClaim:
          #   claimName: code

      initContainers:
        - name: user-app
          image: redeploy/service-user-app:1.0
          volumeMounts:
            - name: code
              mountPath: /var/www/html
          # stdin: true
          # tty: true

      containers:
        - name: php
          image: redeploy/php:rp-7.3-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: code
              mountPath: /var/www/html

        - name: nginx
          image: redeploy/nginx:rp-1.16-p
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: code
              mountPath: /var/www/html

        # - name: mysql
        #   image: redeploy/mysql:latest
        #
        # - name: redis
        #   image: redeploy/redis:latest
