version: '3'
services:

    consul:
      

        build: 
            context: ./
            dockerfile: ./consul/Dockerfile
      
        command: agent -ui -rejoin -retry-join ${CONSUL} -retry-max 10 -retry-interval 10s -node=service-agent-${SERVICE_NAME}
        # entrypoint: 
         

        expose:
            - 53
            - 8300
            - 8301
            - 8302
            - 8400
            - 8500
        ports:
            - 53:53
            - 8300:8300
            - 8301:8301
            - 8302:8302
            - 8400:8400
            - 8500:8500
            - 8600:8600 
        dns:
            - 127.0.0.1
        # network_mode: host
        volumes:
            - "./consul/consul.d/data:/consul/data"
            - "${PROJECT_LOCATION}/${PROJECT_NAME}/${SERVICE_NAME}:/var/www/html"
        environment:    
            - CONSUL_BIND_INTERFACE=eth0
            - CONSUL_CLIENT_INTERFACE=eth0
            - CONSUL_LOCAL_CONFIG={"leave_on_terminate":true}

        
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "${SERVICE_WEB_PORT}:80"
        depends_on:
            - php
            - consul
        environment:    
            - BACKEND=nginx
            - CONSUL=consul
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/log:/var/log/nginx"
            - "${PROJECT_LOCATION}/${PROJECT_NAME}/${SERVICE_NAME}:/usr/share/nginx/html"
        networks:
            - app_net
        container_name: "${SERVICE_NAME}-nginx"


    php:
        build: ./php-fpm
        image: php:7.3-fpm
        depends_on:
            - consul
        links:
            - consul
        environment:
            - BACKEND=php
            - CONSUL=consul
        ports:
            - "${SERVICE_FPM_PORT}:9000"
        volumes:
            - "${PROJECT_LOCATION}/${PROJECT_NAME}/${SERVICE_NAME}:/var/www/html"
        networks:
            - app_net
        container_name: "${SERVICE_NAME}-php"

networks:
    # 配置docker network
    app_net:
        driver: bridge
