version: '3'
services:

    
    nginx:
        image: nginx:latest
        ports:
            - "${SERVICE_WEB_PORT}:80"
        depends_on:
            - "php"
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/log:/var/log/nginx"
            - "${PROJECT_LOCATION}/${PROJECT_NAME}/${SERVICE_NAME}:/usr/share/nginx/html"
        networks:
            - app_net
        container_name: "compose-${SERVICE_NAME}-nginx"


    php:
        build: ./php-fpm
        image: php:7.3-fpm
        ports:
            - "${SERVICE_FPM_PORT}:9000"
        volumes:
            - "${PROJECT_LOCATION}/${PROJECT_NAME}/${SERVICE_NAME}:/var/www/html"
        networks:
            - app_net
        container_name: "compose-${SERVICE_NAME}-php"

networks:
    # 配置docker network
    app_net:
        driver: bridge
