version: '3'
services:

    
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - "php"
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/log:/var/log/nginx"
            - "/var/www/html:/usr/share/nginx/html"
        networks:
            - app_net
        container_name: "compose-nginx"


    php:
        build: ./php-fpm
        image: php:7.3-fpm
        ports:
            - "9090:9000"
        volumes:
            - "/var/www/html:/var/www/html"
        networks:
            - app_net
        container_name: "compose-php"

networks:
    # 配置docker network
    app_net:
        driver: bridge
